# Site settings
title: OpenTomb
email: open.tomb.git@gmail.com
url: https://opentomb.github.io
description: "OpenTomb is a cross-platform reimplementation of classic Tomb Raider 1—5 engines that were developed by now defunct Core Design. It is not a patcher or DLL extension of already existing engines."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: #91819E #645577
  secondary: 293778 #99C2CF
  secondary-dark: A6D1CA #C2D8C3

# Footer settings
footer:
  copyright: Apache v2
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'OpenTomb (formerly TRE) is an engine replacement project intended to play levels from all classic TR games (TR 1-5) and custom levels. It is open-source (GNU GPL3 licensed) and free to use!'

# Build settings
markdown: kramdown
permalink: pretty
