# Site settings
title: OpenTomb
email: open.tomb.git@gmail.com
url: https://opentomb.github.io
description: "OpenTomb is a cross-platform reimplementation of classic Tomb Raider 1—5 engines that were developed by now defunct Core Design. It is not a patcher or DLL extension of already existing engines."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:        bc7340
  secondary:      5C3D17
  secondary-dark: d97c2b

# Footer settings
footer:
  copyright: Apache v2
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/open_tomb
  - title: youtube
    url: https://www.youtube.com/user/Tqbsrc
  - title: github
    url: https://github.com/opentomb/opentomb

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Tomb Raider © & TM Square Enix. OpenTomb is free and open-source (GNU GPL3 licensed) software.'

# Build settings
markdown: kramdown
permalink: pretty
